.gitattributes
Fixes the github programming language percentage thingy. Bit useless, but why not and I checked that it works on the fork.
Doesn't impact any other git functionality, the `linguist-vendor` attribute is only used for code stats.
=> chore: add gitattributes so the gh stats are fixed :)

src/input/action_manifest.rs, src/input/tests.rs, tests/input_data/actions_malformed_paths.json
=> input: properly deduplicate localized action names

src/input.rs, src/input/skeletal.rs
Makes the skeletal tracking level full if getting bones from hand tracking succeeds, unless the controllers are knuckles.
This allows VRChat to enable hand tracking gestures automatically.
=> input: guess skeletal tracking level

src/applications.rs, src/rendermodels.rs
This adds basic implementations to application and rendermodel related functions, which are required for Vivecraft to work.
These should probably be properly implemented in the future, but for now this seems fine to get something functional.
=> Partially implement stubbed functions for Vivecraft support

src/misc_unknown.rs
Perhaps it's giving us a null pointer?
=> misc_unknown: fix alyx assert in undoc3

src/input.rs, src/input/action_manifest.rs, src/input/legacy.rs, src/input/profiles.rs, src/input/profiles/knuckles.rs, src/input/profiles/oculus_touch.rs, src/input/profiles/simple_controller.rs, src/input/profiles/vive_controller.rs, src/input/skeletal.rs, src/input/skeletal_generated.rs, src/input/tests.rs
This fixes the estimated hand skeleton being wonky (including with Quest controllers) and enables full control for the fingers with interpolation at a set speed.
So far has been tested with Quest controllers in VRChat, Resonite and HL:A
=> Estimated skeleton rework

src/input.rs, src/input/action_manifest.rs, src/input/action_manifest/helpers.rs, src/input/action_manifest_helpers.rs, src/input/custom_bindings.rs, src/input/profiles/knuckles.rs, src/input/profiles/oculus_touch.rs, src/input/profiles/vive_controller.rs, src/input/tests.rs, tests/input_data/actions.json, tests/input_data/actions_dpad_multi.json, tests/input_data/knuckles.json, tests/input_data/knuckles_dpad_thumbstick.json
This PR includes the following changes to the input system:
* Store custom binding information per-profile and per-hand explicitly
* Most (all?) bindings in SteamVR are specifying only one hand as input source anyway
* This incidentally allows detecting action origin for custom bindings, which is used when possible
* This also prevents cross-contamination of custom bindings between different profiles/controller types.
* Custom binding information and state is stored separately from actions
* Adjusted index controller grip thresholds to be in-line with SteamVR
* This changes how the "grab" action is read as a `f32` - it's now binary 0/1 and never returns any inbetween values. A common `f32` binding type for grip seems to be "trigger" or "force_sensor", but if you have examples of games …
=> Bindings rework

openvr/build.rs, src/clientcore.rs, src/lib.rs, src/settings.rs
The most basic `IVRSettings` stub that returns zeroes and ignores writes while logging everything.
This upgrades Vivecraft from no-launch to playable (tested with WiVRn+q3).
=> IVRSettings stub

src/compositor.rs, src/openxr_data.rs, src/overlay.rs
Some older games and mods use curved overlays, this makes them actually curved properly.
I know from my wlx-related research that this lines up exactly with what SteamVR would show. Looked good in testing as well.
Feedback is very welcome.
=> Support overlay curvature

src/compositor.rs, src/openxr_data.rs, src/overlay.rs
Skybox will show over the projection layers if FadeGrid is used. Most apps use this in conjunction with SuspendRendering which I implemented by feeding into xr's should_render.
Skybox elements are overlays without an entry in key_to_overlay so that the client app won't have access to them. It made sense to re-use the overlay implementation.
Overlays are now sorted by z_order ascending. We should someday also take into account distance to hmd, but I guess this is one step in the right direction.
lifetime_extend is still ugly but idk what to do with it.
Tested with vrc where this behaves correctly. Feel free to mention other titles that use this because I don't know any.
=> Support skybox & overlay sort order

shaders/src/overlay.frag, src/graphics_backends/vulkan.rs, src/overlay.rs
Current state of affairs:
Alpha is rendered into the swapchain when SetOverlayTexture is called.
Upon SetOverlayAlpha call, the swapchain is not updated, so the alpha stays the same until the next SetOverlayTexture.
=> Overlay alpha corrections

src/compositor.rs
Minor refactor to avoid the `unsafe { std::ptr::read(&new_info) }` workaround.
=> compositor: refactor swapchain re-creation check

shaders/src/overlay.frag, src/compositor.rs, src/graphics_backends.rs, src/graphics_backends/gl.rs, src/graphics_backends/vulkan.rs, src/openxr_data.rs, src/overlay.rs
I refactored OverlayLayer into CompositorLayer and moved it into compositor.rs
adding to next chains in openxrs is always a pain, I tried to make it as isolated as possible
KHR_composition_layer_color_scale_bias is implemented by monado, but not enabled by default. we can have envision/wivrn enable it by default if it comes to that. i just tested by enabling it on wivrn.
also fixes the bounds using wrong dimensions
this gives a perfect loading screen in vrc, unless looking from a weird angle.
=> implement overlay alpha using KHR_composition_layer_color_scale_bias

src/compositor.rs, src/graphics_backends/gl.rs
This fixes vivecraft on 1.20.4 being too bright. The behavior should to be in-line with descriptions of `EColorSpace`, although I'm not aware of any other games using OpenGL to verify possible breakage in the other direction.
=> Handle gamma space textures on opengl backend

src/overlay.rs
During our investigation of #80 , we reached a point where everything in the game worked, except for one point: when trying to connect to multiplayer using the "Quantum Space Buddies" mod in addition to NomaiVR, xrizer panicked due to the unimplemented function `ShowKeyboard`.
By removing the `todo!()` panic call, and instead returning an enum variant to alert the game that the keyboard could not be shown properly to the user, the game can continue on and let the user fill the text field using another way (e.g. desktop keyboard), and thus the game becomes entirely playable.
I do not foresee this change leading to any regression, given that xrizer would have panicked in this situation anyway. But you may have a better idea in mind for replacing this panic call.
=> Return dummy failure state on ShowKeyboard

xbuild/src/main.rs
I actually tested both cases this time, sorry about that
Fixes 0fe0c6f044c16c0513d19aab3f40779e7ae576b4
=> xbuild: Actually fix directory name build issue

src/input.rs, src/input/action_manifest.rs, src/overlay.rs
Fixes: https://github.com/Supreeeme/xrizer/issues/122
Adds IVROverlay_IVROverlay_020_SetOverlayInputMethod with an unimplemented warning with the two types.
Adds the Tip type used in the action profile of The Lab for Oculus touch controllers
=> Fix IVROverlay_IVROverlay_020_SetOverlayInputMethod not yet implemented [The LAB]

src/overlay.rs
this fixes After the Fall
the game calls overlay-related input methods during loading screens, even though overlay input seems to not be used at all.
=> dummy SetOverlayMouseScale

src/input/action_manifest.rs, src/input/custom_bindings.rs, src/input/tests.rs, tests/input_data/actions.json, tests/input_data/oculus.json
Some (most?) controllers lack capsense on their grip trigger (oculus touch being prime example). SteamVR will trigger the "touch" output of "trigger" mode bindings on any non-zero amount of press. This change implements this behavior.
This affects the fist gesture in VRChat when using Touch controllers: before, it would only trigger the fist around 50% press value, resulting in non-smooth experience on avatars using gesture weight. With this change, the fist gesture is triggered immediately when starting to press the grip.
[LVRA Discord discussion](https://discord.com/channels/1065291958328758352/1325368274921459843/1385018244200530073)
=> Implement a fallback for "touch" output on "trigger" mode bindings

xbuild/openvrpaths.vrpath.in, xbuild/src/main.rs
This creates a bundled vrpaths config at the build location or one manually specified during xbuild so openvr runtime switching can be made as simple as symlinking to it.
=> Template build vrpaths config for distribution packaging

src/compositor.rs, src/input.rs
This resolves startup panics and looks to get poses working.
I can't quite test this with my real hardware, I'm still trying to figure out how to get the 32-bit stuff working properly. Monado's simulated HMD view looks correct though.
Should also fix a panic in Half-Life: Alyx in `SetDominantHand` when the dominant hand setting is changed. The game has its own internal dominant hand setting, so I think it just calls that to hint SteamVR to load the left/right-handed bindings.
`GetLastPoseForTrackedDeviceIndex` was scavenged from #176 and modified to not need extra helper functions.
=> Just enough to get HL2VR to start
